version: '3'
services:
  my-mongo:
    image: mongo:4.2.2
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
    ports:
      - "27017:27017"
 
volumes:
  db-data:
  mongo-config:
